mm-easy/mm-easy

src/components/common/PageUpBtn.tsx, src/components/quiz-form/QuizForm.tsx, src/types/quizzes.ts, src/utils/supabase/middleware.ts
#11 
* `components / common/ PageUpBtn.tsx` 입니다. 스크롤이 아래로 400px 이상 이동되면 이미지가 표시되고, 이미지를 클릭하면 맨 위로 스크롤이 이동합니다.
* 현재 임시 이미지 & 임시 크기 적용되어 있습니다.
* 사용하시는 방법:
1. 컴포넌트에 스크롤 위치를 추적하기 위한 상태를 만듭니다. (클라이언트 컴포넌트 필수)
```
const [scrollPosition, setScrollPosition] = useState<number>(0);
```
2. 스크롤을 감지하는 useEffect 훅을 작성해줍니다.
```
const handleScroll = () => {
setScrollPosition(window.scrollY);
};
window.addEventListener('scroll', handleScroll, { passive: true });
return () => {
window.removeEventListener('scroll', handleScroll);
};
}, [scrollPosition]);
```
3. PageUpBtn 컴포넌트를 찾기 편하신 곳에 넣어주고, 위치를 고정해줍니다. 아래의 내용으로 입력하시면 우하단에 고정됩니다.
```
<div style={{ position: 'fixed', bottom: '20px', right: '20px;' }}>
<PageUpBtn scrollPosition={scrollPosition} />
</div>
```
=> [feat] PageUp 버튼 컴포넌트 추가

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/components/layout/Header.tsx, src/hooks/useAuth.ts, src/types/users.ts
#20 
로그인시 이메일 확인이 안됫다는 문구가 출력되며 로그인이 되지않는 상황이 발생함
- 회원가입시 supabase 이메일 확인이 켜져있는것이 문제발생의 이유 이메일 확인 비활성화로 해결
회원가입시 정보가 profiles 테이블에 추가되지않는 문제 발생
- supabase profiles 테이블의 RLS 를 disable 함으로 해결
임의로 이메일을 만들어 회원가입할시 supabase 이메일 확인을 꺼둘것!
=> [feat] 회원가입시 profiles 에 정보 추가, 로그인 기능 구현

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/terms/page.tsx, src/app/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-138 
로그인 페이지에서 회원가입으로 이동할시 이용약관 페이지로 먼저 가지게 했고, 이용약관 동의를 하지않으면 넘어가지지 않게 했습니다.
사용자 정보를 받아오는 로직을 작성했음에도 받아오지 못했던 문제가 있었는데,
supabase 에서 RLS를 비활성화 함으로써 해결됌
=> [feat] 사용자 정보 패칭, 이용약관 페이지 구현

src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-131
🔗 https://coding-legend.atlassian.net/browse/MMEASY-118
🔗 https://coding-legend.atlassian.net/browse/MMEASY-122
- 체크박스들을 따로 모아서 정답, 오답별로 state 변경을 해야 하나..? 했는데
그냥 옵션에 isAnswer 를 내려주면 되는 문제였습니다.. (체크 하나씩, 정답 처리가 같이 해결되었어요 🥹)
- name 속성은 지금 필요없는 것 같아서 지웠습니다!
```tsx
<input
type="checkbox"
checked={option.isAnswer}
onChange={() => {
handleCheckObjectAnswer(id, options, option.id);
}}
/>
```
- 리액트 체크박스 검색하다 찾은 영상인데 7분즈음 disabled 약관동의에 활용하면 좋을거 같아요.
근데 지금 toast도 좋습니다.. 한 번 고민을..!
🔗 https://www.youtube.com/watch?v=w7gIFDw0Hoc
=> [feat] 선택지 체크 시 정답으로 설정, 헤더 로고 클릭 시 홈으로 이동

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/app/(non-auth)/terms/page.tsx, src/app/page.tsx, src/components/layout/Header.tsx, src/hooks/useAuth.ts, src/store/store.ts
🔗https://coding-legend.atlassian.net/browse/MMEASY-164 
소셜 로그인이 아닌 일반 로그인시에는 로그인 로그아웃이 잘 렌더링 되었지만, 
소셜 로그인으로 로그인시 바뀌지 않는 문제가 발생해 알아본 결과 소셜 로그인은 다른 외부 페이지에서 로그인 하기 때문에 onAuthStateChange 메서드가 감지하지 못함. 따라서 getUser 메서드를 사용해 소셜 로그인 후 가져온 유저 정보를 바탕으로 렌더링 되게 해결
=> [feat] 헤더 로그인 상태에 따라 로그인,로그아웃 조건부 렌더링

src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-161
- 체크박스 커스텀하다가 checked:bg-[url('**여기**')] 부분에 파일 경로를 넣어야 하는데,
절대.. 안들어가서 supabase 로 이미지 링크 넣어놨습니다. 로컬에 만들었던 assets 폴더는 우선 지웠습니다.
- 체크박스 배경색은 pointColor1 로 넣었고, 그 위에 화이트 체크표시.png 들어갔습니다.
- 체크표시 사이즈 bg-md 로 조절했습니다.
- appearance-none 이 원래 체크박스 디자인 없애줍니다!
QustionForm.tsx
```tsx
<input
type="checkbox"
checked={option.isAnswer}
className="w-11 h-11 appearance-none border-solid border border-pointColor1 rounded-md checked:bg-pointColor1 
checked:bg-[url('https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public/assets/checkbox.png')]
bg-md bg-no-repeat bg-center"
onChange={() => {
handleCheckObjectAnswer(id, options, option.id);
}}
/>
```
- supabase assets 폴더 추가했는데 여기서 계속 가져와도 좋을 거 같습니다..
﻿
- tailwind.config 에 이 부분 지워도 될 거 같아요..? …
=> [style] question CSS, tailwind.config 에 backgroundSize 추가

src/app/(quiz)/(components)/InputQuestionImg.tsx, src/app/(quiz)/(components)/InputQuestionTitle.tsx, src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/SelectQuestionType.tsx, src/app/(quiz)/quiz-try/page.tsx, src/components/common/SubHeader.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-167
- 선택형, 주관형 부분을 공통 컴포넌트로 묶었는데,
내려주는 값이 많아서 분리하는게 맞는지 고민입니다..
QustionForm.tsx
- 분리 전
```tsx
<label className="pr-4">
<input
type="radio"
name={id}
defaultChecked
className="mr-2"
onChange={() => handleChangeType(id, QuestionType.objective)}
/>
선택형
</label>
<label>
<input
type="radio"
name={id}
className="mr-2"
onChange={() => handleChangeType(id, QuestionType.subjective)}
/>
주관형
</label>
```
- 분리 후
```tsx
<SelectQuestionType
id={id}
defaultChecked={true}
onChange={handleChangeType}
type={QuestionType.objective}
title="선택형"
/>
<SelectQuestionType
id={id}
defaultChecked={false}
onChange={handleChangeType}
type={QuestionType.subjective}
title="주관형"
/>
```
=> [feat] question 내 중복 태그들 컴포넌트로 분리

next.config.mjs, src/api/quizzes.ts, src/app/(quiz)/(components)/QuizForm.tsx, src/app/(quiz)/(components)/QuizList.tsx, src/app/(quiz)/(components)/SelectQuizLevel.tsx, src/app/(quiz)/quiz-list/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-132
🔗 https://coding-legend.atlassian.net/browse/MMEASY-133
🔗 https://coding-legend.atlassian.net/browse/MMEASY-159
`quiz-list` 기능을 대강 구현했습니다. 그런데 전체 레벨 모아보기 기능이 추가되면 더 좋을 것 같아요. 그리고 기획 초반에 잠시 얘기 나왔던 퀴즈 카테고리도 추가해보면 더 좋을 것 같습니다.
flex flex-wrap gap-4 이런식으로 했더니 제일 오른쪽 항목에도 오른쪽에 gap이 생겨서 가운데 정렬이 어려웠는데 grid 썼더니 해결됐습니다. 매번 flex만 도배하는데 grid가 이렇게 유용하네요! 근데 브라우저 너비가 줄어들면 요소들이 겹쳐지는 문제점이 있습니다. 나중에 해결하겠습니다..
```
<div className="w-8/12 grid grid-cols-4 mt-5 place-items-center">
{quizLevelSelected.map((item) => (
<div key={item.id} className="flex flex-col gap-3 mb-8">
<div className="border-solid border border-pointColor1 rounded-md overflow-hidden w-[250px] h-[250px]">
<Image
src={`https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public/qui …
```
=> [feat] quizzes 테이블에서 불러와서 출력

src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-209
- className 이 많이 길어서.. h2, h3 를 컴포넌트로 나누거나 header 를 분리해두면 좋을 거 같습니다.
- text 부분들을 8% 로 두고, 생명 표시 부분을 60% 로 맞췄습니다.
- className 벡틱으로 쓰고 style={} 없애려 했는데 적용이 안되네요.. 🥲
```tsx
<div className="h-[calc(8vh-2px)] bg-pointColor2" style={{ width: `${lifePercentage}%` }}></div>
```
- calc 를 쓰면 크기 연산이 가능합니다!
```css
.example {
font-size: calc(2vw + 10px); /* viewport width에 따라 크기 조절하면서 10px를 추가 */
padding: 20px; /* 고정된 크기로 픽셀 단위 사용 */
margin: calc(1vw + 5px) calc(2vw + 10px); /* 세로는 viewport width에 따라, 가로는 픽셀 단위로 사용 */
width: calc(50% + 20px); /* 백분율로 지정하면서 20px를 추가 */
}
```
=> [style] 타자연습 페이지 레이아웃 CSS

src/app/(quiz)/(components)/QuizForm.tsx, src/hooks/useConfirmPageLeave.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-225
* 새로고침, 창 닫기 시 경고 띄우게 했습니다. 뒤로가기도 추가해야 하는데 쉽지 않네요.
Next.js 13? 14버전부터 router를 import할 때 next/router가 아니라 next/navigation에서 가져와야 하는데,
next/navigation에는 이전 버전에서 해당 처리 시 사용했던 기능이 없어서 다른 방법을 써야한대요.
챗지피티가 계속 예전 버전 방식만 알려줘서 구글링 많이 해봐야 할 것 같습니다.
* 현재는 새로고침, 창 닫기 시도할 때 무조건 경고가 뜨는데, input에 입력값이 발생했을 때 경고가 뜨게끔 디벨롭 하면 더 좋을 것 같습니다.
```
const handleBeforeUnload = (event: BeforeUnloadEvent) => {
event.preventDefault();
event.returnValue = '';
return '작성하던 내용이 모두 사라집니다. 계속하시겠습니까?';
};
const handlePageUnload = () => {
if (!window.confirm('작성하던 내용이 모두 사라집니다. 계속하시겠습니까?')) return;
};
window.addEventListener('beforeunload', handleBeforeUnload);
window.addEventListener('unload', handlePageUnload);
return () => { …
```
=> [feat] quiz-form 새로고침/브라우저 닫을 때 경고

src/app/(quiz)/quiz/[id]/Options.tsx, src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-226
- queryKey 에 원래 'question_options' 만 적었었는데, 같은 쿼리키로 옵션들을 요청하고 있어서
이미 로드된 데이터라고 인식해 재요청을 하지 않아 생긴 문제였습니다.
- 뒤에 questionId 를 추가해 고유한 쿼리키가 되도록 수정했습니다.
Options.tsx
```tsx
const { data, isLoading, isError } = useQuery({
queryFn: async () => {
try {
const data = await getOptions(questionId);
return data;
return error;
}
},
queryKey: ['question_options', questionId]
});
```
- 맵을 돌린 questio_id 는 여러개가 잘 출력되는데, 실제 요청은 한 번만 이루어지고 있었습니다..
- 쿼리키 수정하니 question 마다 잘 출력됩니다!
=> [fix] 문제마다 같은 옵션 불러와지는 에러

src/app/(quiz)/(components)/QuizForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-171
🔗 https://coding-legend.atlassian.net/browse/MMEASY-208
- 퀴즈 등록하기 만들어주신 거에 for of 문 추가해서 구현했습니다.
- 난이도, 제목, 설명 alert => toast 로 변경했습니다.
- 등록하실 때 쓴 question 프로퍼티들 구조 분해해놨습니다!
Quiz_form.tsx
```tsx
for (const question of questions) {
const { title, type, correct_answer, options } = question;
const allAnswersAarFalse = options.every((option) => option.is_answer === false);
if (!title) {
toast.warn('제목을 입력해 주세요.');
return;
}
if (type === QuestionType.objective) {
for (const option of options) {
const { content } = option;
if (!content) {
toast.warn('선택지를 입력해 주세요.');
return;
}
}
if (allAnswersAarFalse) {
toast.warn('정답을 선택해 주세요.');
return;
}
}
if (!correct_answer) {
toast.warn('정답을 입력해 주세요.');
return;
}
}
```
=> [fix] 퀘스천 제목, 정답들이 비어있거나 선택형에서 정답 체크가 안되있을 시 워닝 toast

src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-249
- 정답이면 파란색으로, 아니면 빨간색 보더로 구분했습니다. (테일윈드도 조건부 렌더링이 되더군요..)
```tsx
<p className={`w-full pl-4 py-[9px] border-solid border
${usersAnswer?.answer === correct_answer ? ' border-pointColor1' : 'border-pointColor2'} rounded-md`}>
{usersAnswer?.answer}
</p>
```
- 조건부 렌더링 참고 링크입니다.
🔗 https://sezzled.tistory.com/13
=> [feat] 결과 페이지에서 주관형 정답/오답 조건부 렌더링

src/app/(quiz)/quiz/[id]/Header.tsx, src/app/(quiz)/quiz/[id]/Options.tsx, src/app/(quiz)/quiz/[id]/page.tsx, src/components/layout/Header.tsx, src/types/quizzes.ts, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-250
- 결과모드이고 사용자가 선택한 아이디 === 옵션 아이디인 상황에서 정답/오답을 구분했습니다.
- 정답이면 파란색 배경&보더, 아니면 빨간색 배경&보더로 구분했습니다.
- 분홍색 배경이 필요해서 tailwind.config 에 추가해뒀습니다.
Options.tsx
```tsx
<div key={id} className={`pl-4 py-[9px] flex gap-4 border-solid border
${resultMode && usersAnswer?.option_id === id ? (is_answer ?
'border-pointColor1 bg-bgColor2' : 'border-pointColor2 bg-bgColor3')
: 'border-pointColor1'} rounded-md`}
>
```
=> [feat] 결과 페이지에서 선택형 정답/오답 조건부 렌더링 및 좌측 퀴즈 정보 비율 16%로 수정

middleware.ts, src/app/(community)/community-list/page.tsx, src/app/(main)/(components)/CommunitySection.tsx, src/app/(quiz)/(components)/QuizForm.tsx, src/app/page.tsx, src/app/profile/page.tsx, src/components/layout/Header.tsx, src/hooks/useAuth.ts, src/types/users.ts, src/utils/supabase/client.ts, src/utils/supabase/create-client.ts, src/utils/supabase/supabase.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-44
🔗 https://coding-legend.atlassian.net/browse/MMEASY-164
* 이제 로그인을 했을 때 토큰 정보가 로컬스토리지에 저장되지 않고 쿠키에 저장됩니다. 토큰 정보를 불러올때는 `await supabase.auth.getSession()`을 사용하시면 됩니다.
* 세션 정보가 있는지(로그인 되어 있는 상태인지) 확인하는 코드와, 세션 정보가 있다면 profiles 테이블에서 세부 프로필 정보를 가져오는 코드를 하나의 useEffect 안에 작성하려고 했는데 어려웠습니다.
* 새로고침 시 로그인 상태 유지 이슈를 해결하면 로그아웃 시 403 forbidden 에러가 뜨고, 403 forbidden 에러를 해결하면 새로고침 시 로그인 상태가 유지되지 않아서
* 다른 의존성배열을 갖고 있는 useEffect 2개를 활용하여 로직을 나누어 해결했습니다..
* 더 좋은 아이디어 있으시면 말씀주세요..
```
/** 현재 로그인되어 있는지 확인 */
const fetchData = async () => {
try {
const getSession = await supabase.auth.getSession();
if (!getSession.data.session) {
return;
} else {
setIsLoggedIn(true);
}
console.error('프로필 정보를 가져오는 데 실패했습니다:', error);
} …
```
=> [feat] supabase SSR 방식으로 변경... 그리고 헤더 수정

src/api/profiles.ts, src/app/(quiz)/quiz/[id]/Creator.tsx, src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-242
- creator 이메일을 받아 profiles 테이블에서 닉네임 가져왔습니다.
- 같은 닉네임이 계속 표시됐었는데 쿼리키에 creator 추가해서 해결했습니다.
Creator.tsx
```tsx
const Creator = ({ creator }: { creator: string }) => {
const { data, isLoading, isError } = useQuery({
queryFn: async () => {
try {
const data = await getProfile(creator);
return data;
return error;
}
},
queryKey: ['profiles', creator]
});
```
- 쿼리키 수정 전
- 쿼리키 수정 후
- 풀기 페이지를 들어가면 잠깐 다른 문제가 뜨고 있네요..
=> [feat] 풀기 페이지에 퀴즈 작성자 정보 email => nickname 으로 변경

src/api/tries.ts, src/app/(quiz)/quiz/[id]/Creator.tsx, src/app/(quiz)/quiz/[id]/page.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-282
🔗 https://coding-legend.atlassian.net/browse/MMEASY-281
Header.tsx
useAuth.tsx
프로필이 없을 때 그냥 return 이 아닌 return null 으로 설정하신게 궁금합니다. 😲
없는 값인 걸 확실히 하는걸까요?
=> [fix] 퀴즈 풀기 페이지 로그인 확인 & 프로필 요청 useEffect 분리, 의존성 배열 수정

src/app/(quiz)/quiz/[id]/Creator.tsx, src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-270
- 가져온 question 의 img_url 이 기본 이미지명이랑 같다면 표시되지 않게 했습니다.
```tsx
{img_url !== 'tempThumbnail.png' ? (
<Image
src={`https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public/question-imgs/${img_url}`}
alt="문제 이미지"
width={570}
height={200}
className="h-[200px] object-cover rounded-md"
/>
) : (
<></>
)}
```
=> [fix] 사용자가 이미지를 등록하지 않은 question 은 기본 이미지도 표시 X

src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx, src/components/common/BlueInput.tsx, src/components/common/SubHeader.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-368
=> [style] quiz-form 페이지 파일첨부 이전 기본이미지 적용

src/api/quizzes.ts, src/app/(main)/(components)/QuestionEx.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(quiz)/(components)/QuizForm.tsx, src/app/(quiz)/(components)/QuizList.tsx, src/app/(quiz)/quiz/[id]/page.tsx, src/utils/getRandomThumbnail.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-370
🔗 https://coding-legend.atlassian.net/browse/MMEASY-371
썸네일 이미지 주소가 들어 있는 배열을 만들어서 랜덤 인덱스를 추출하는 함수를 만들었습니다
```ts
export const getRandomThumbnail = (): string => {
const thumbnails = ['quiz_thumb_1.png', 'quiz_thumb_2.png', 'quiz_thumb_3.png'];
const randomIndex = Math.floor(Math.random() * thumbnails.length);
return thumbnails[randomIndex];
};
```
첨부한 이미지가 없을때(imgUrl === null) 위의 함수를 실행시켜 랜덤 이미지 주소를 얻습니다
```tsx
// newQuiz 구성하여 quizzes 테이블에 인서트
const newQuiz = {
creator_id: currentUser,
level,
title,
info,
thumbnail_img_url: imgUrl || getRandomThumbnail()
};
const insertQuizResult = await insertQuizMutation.mutateAsync(newQuiz);
```
=> [style] quiz-form 랜덤 기본 썸네일 지정, quiz-list 퀴즈 배열 수정

src/api/posts.ts, src/app/(community)/(components)/CommunityForm.tsx, src/app/(main)/(components)/CommunitySection.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-399
```
export const getRecentPosts = async () => {
const { data: posts, error } = await supabase
.from('posts')
.select('*')
.neq('category', '공지')  // category가 공지가 아닌것만
.is('deleted_at', null). // deleted_at이 null 인것만
.order('created_at', { ascending: false }) // 최신 게시글부터 정렬
.limit(3); // 3개의 게시글만 가져옴
export const getRecentNotice = async () => {
const { data: posts, error } = await supabase
.from('posts')
.select('*')
.eq('category', '공지')  // category가 공지 인것만
.is('deleted_at', null)  // deleted_at이 null 인것만
.order('created_at', { ascending: false }) // 최신 게시글부터 정렬
.limit(3); // 3개의 게시글만 가져옴
```
=> [feat] 메인페이지 공지 표시

src/api/quizzes.ts, src/app/admin/page.tsx, src/app/my-activity/MyActivity.tsx, src/hooks/useAuth.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-405
🔗https://coding-legend.atlassian.net/browse/MMEASY-414
- 관리자 페이지에 접근 시 어드민 계정이 아닐경우 조건부 랜더링을 통해 랜더링을 막았습니다.
- 나의 활동 페이지에 내가 만든 퀴즈가 불러와지지 않는 오류 수정했습니다.
- 기존에는 내가 만든 퀴즈가 잘 가져와졌으나, 사용하던 api 가 quiz 와 question 에 외래키 연결을 추가하면서
문제가 발생했었습니다. 해당 문제는 api 호출 시 가져오는 데이터가 question 의 외래키 부분이랑 혼란이 있을 수 있어서 
데이터를 가져오지 못했던 오류로 데이터를 명시적으로 적어주어 해결했습니다.
```
export const fetchUserQuizzes = async (email: string) => {
try {
const { data, error } = await supabase
.from('quizzes')
.select(`
*,
quiz_tries:quiz_tries!public_quiz_tries_quiz_id_fkey(id)
`)
.eq('creator_id', email);
if (error) throw error;
return data;
console.error('사용자 퀴즈 불러오기 실패', error);
}
};
```
=> [feat] 관리자 페이지 조건부 랜더링 및 나의 활동 오류수정

src/app/(community)/(components)/CommunityForm.tsx, src/app/typing-game/page.tsx, src/types/difficultySetting.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-421
🔗 https://coding-legend.atlassian.net/browse/MMEASY-422
useMemo 와 sort 사용해 커뮤니티 공지글 상단으로 고정되게 구현했습니다.
```
const sortedItems = useMemo(() => {
return [...currentItems].sort((a, b) => {
if (a.category === '공지' && b.category !== '공지') {
return -1; // a가 공지이면, b보다 앞에 오도록 정렬
}
if (a.category !== '공지' && b.category === '공지') {
return 1; // b가 공지이면, a보다 앞에 오도록 정렬
}
return 0; // 두 항목이 모두 공지이거나 공지가 아닐 경우 기본 순서 유지
});
}, [currentItems]);
```
=> [feat] 타자연습 난이도 명 변경, 커뮤니티 공지 상단 고정

src/app/(quiz)/quiz/[id]/Options.tsx, src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-431
- page state 를 만들어서 그 페이지에 맞는 문제가 표시되도록 했습니다.
- 처음/마지막 페이지는 버튼이 클릭되지 않도록 했습니다.
```tsx
const handlePrevPage = () => {
setPage(page - 1);
};
const handleNextPage = () => {
setPage(page + 1);
};
<button disabled={page === 0} onClick={handlePrevPage}>
이전 페이지
</button>
<button disabled={page === questions.length - 1} onClick={handleNextPage}>
다음 페이지
</button>
```
- 긴 문제는 문제 영역 height 고정 시켜두고 스크롤이 생기게 하려고 했는데.. 담에 다시 도전해보겠습니다..
=> [feat] 문제 페이지네이션 기능 구현 및 버튼 구성 & 결과 페이지에선 모든 문제 표시

src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/community/list/[category]/CommunityForm.tsx, src/app/community/list/[category]/[id]/Comment.tsx, src/app/layout.tsx, src/app/my-activity/MyActivity.tsx, src/app/page.tsx, src/app/quiz/[id]/page.tsx, src/app/quiz/form/PlusQuestionBtn.tsx, src/app/quiz/form/QuestionForm.tsx, src/app/quiz/form/QuizForm.tsx, src/app/quiz/list/QuizList.tsx, src/app/typing-game/page.tsx, src/components/common/PageUpBtn.tsx, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-442
🔗 https://coding-legend.atlassian.net/browse/MMEASY-443
- body 에 베이지 컬러를 깔고 가운데 저희 컨텐츠 넣는 쪽을 화이트로 깔았습니다!
메인만 변경을 해놔서 아직 다른 메뉴는 베이지가 배경인 곳이 있을 거에요.
app/layout.tsx
```tsx
<body className={`bg-bgColor1 ${gothic_a1.className}`}>
<main className="mx-auto bg-white lg:w-[1444px] lg:border-x-2 lg:border-solid lg:border-pointColor1 md:w-full">
```
- 기존에 넣어놨던 진한 그레이컬러를 grayColor2로 두고, gray-200 으로 사용하고 있던 연한 그레이를 grayColor1으로 넣어놨습니다!
사용하시던 곳은 수정해놨습니다!
- 페이지업버튼을 어찌해야할지 고민입니다..
=> [style] tailwind screens lg(min: 1441px), md(min:861px) 설정 & 메인페이지 lg 레이아웃 수정

src/app/community/list/[category]/CommunityForm.tsx, src/app/community/list/[category]/CommunityMain.tsx, src/app/community/list/[category]/[id]/DetailPost.tsx, src/app/community/write/layout.tsx, src/app/community/write/page.tsx, src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-466
- 흰 배경 부분 padding-x 5vw 로 잡아놨습니다! 각각 아래가 변경 후 사진입니다.
=> [style] 타자연습 헤더 텍스트 영역 너비 늘림 & 커뮤니티 글 영역 padding 반응형으로 수정

src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-475
=> [fix] 타자연습 오디오 파일 페이지 넘어가면 재생 중지

src/app/(main)/QuizSection.tsx, src/app/about/page.tsx, src/app/profile/MyProfile.tsx, src/app/quiz/[id]/PageAndSubmitBtn.tsx, src/app/quiz/list/QuizList.tsx, src/app/quiz/list/SelectQuizLevel.tsx, src/components/common/FormButtons.tsx, src/components/layout/ProfileDropdown.tsx, src/constant/locales/my-page/my-profile.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-609
🔗 https://coding-legend.atlassian.net/browse/MMEASY-610
🔗 https://coding-legend.atlassian.net/browse/MMEASY-611
🔗 https://coding-legend.atlassian.net/browse/MMEASY-612
🔗 https://coding-legend.atlassian.net/browse/MMEASY-613
- next ui 컬러 변경 방법입니다! 불러왔던 Avatar 를 MyAvatar 로 다시 지정해줬습니다!
ProfileDropdown.tsx
```tsx
import { extendVariants, DropdownItem, DropdownTrigger, Dropdown, DropdownMenu, Avatar } from '@nextui-org/react';
const MyAvatar = extendVariants(Avatar, {
variants: {
color: {
white: {
base: ['bg-white']
}
}
},
defaultVariants: {
color: 'white'
}
});
```
- 퀴즈 리스트에 레벨 이미지 높이를 메인 배너 부분이랑 맞춰놨는데, 혹시 너무 길면 말씀해 주세요!
=> [fix/style] 퀴즈, 프로필, 메인 자잘한 CSS & 메인 관리자 퀴즈 표시

src/app/community/list/[category]/[id]/Comment.tsx, src/app/community/list/[category]/[id]/DetailPost.tsx, src/app/community/list/[category]/[id]/edit/page.tsx, src/app/community/write/PostEditor.tsx, src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/QuizDorpdown.tsx, src/app/quiz/[id]/SideHeader.tsx, src/app/quiz/[id]/page.tsx, src/components/common/DeleteButton.tsx, src/components/common/DropdownMenu.tsx, src/components/common/EditButton.tsx, src/components/common/FormButtons.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-622
현재 퀴즈에 삭제 드롭다운 넣긴 했는데 본인 게시글만 조건부 렌더링 추가해야 합니다.. 일단은 로직 넣기 전까진 드롭다운
주석처리 해둔 상태로 올립니다..!
- Header.tsx
```tsx
<div className='pr-4 font-bold'>
{/* <QuizDropdown
deleteBtn={
<CancelButton
text={m('DELETE_BTN')}
width="w-32"
height="h-12"
border="border-1"
onClick={() => handleDeleteQuiz(id as string)}
/>
}
/> */}
</div>
```
드롭다운에 조건부 렌더링 추가해야합니다!
=> [feat] 퀴즈 풀기 페이지 삭제버튼 추가
