mm-easy/mm-easy

src/app/(quiz)/quiz-form/page.tsx, src/app/(quiz)/quiz-list/page.tsx, src/app/(quiz)/quiz-try/page.tsx, src/app/quiz/page.tsx, src/components/quiz-form/QuestionForm.tsx, src/components/quiz-form/QuizForm.tsx
=> [feat] quiz-form 페이지 관련 폴더링/파일 생성

next.config.mjs, src/components/quiz-form/QuestionForm.tsx
closed #4 
```
```
- 지영님이 보내주신 via fake image 주소 Image 태그에 넣으니 hostname error 떠서 next.config.mjs 에 주소 추가했습니다!
=> [feat] question-form 브랜치 생성 및 간단한 form 구성

src/components/quiz-form/QuestionForm.tsx, src/components/quiz-form/QuizForm.tsx
#8 
quiz-form 컴포넌트의 `form`태그 안에 question-form 컴포넌트의 `form`태그가 중첩되어 발생한 오류를 해결했습니다.
=> [feat] quiz-form & question-form 머지

package.json, src/app/(community)/community-detail/page.tsx, src/app/(community)/community-list/page.tsx, src/app/(community)/community-post/page.tsx, src/app/community/page.tsx, src/components/community/community-comment/CommentForm.tsx, src/components/community/community-form/CommunityForm.tsx, src/components/community/community-form/PostForm.tsx, src/components/community/like/Like.tsx, src/utils/supabase/client.ts, src/utils/supabase/create-client.ts, src/utils/supabase/server.ts, yarn.lock
#10 #15
utils\supabase\create-client 파일 추가했습니다. 서버 사이드에서 활용할 파일이고
앞으로 createClient 하실 때 경로가 /utils/supabase/create-client 인지 잘 확인하셔서 사용하시면 되겠습니다.
추가로 첨부 스크린샷 처럼
const supabase = createClient() 넣어주시면 됩니다
```
```
=> [feat] utils\supabase\create-client 파일 추가 및 브랜치 세팅

src/components/quiz-form/QuestionForm.tsx, src/components/quiz-form/QuizForm.tsx, src/types/quizzes.ts
closed #18 
- questions 초기값입니다.
QuizForm.tsx
```tsx
const [questions, setQuestions] = useState<Question[]>([
{
id: crypto.randomUUID(),
type: QuestionType.objective,
title: '',
options: [
{
id: crypto.randomUUID(),
content: '',
isAnswer: false
},
{
id: crypto.randomUUID(),
content: '',
isAnswer: false
}
]
// imgUrl: '',
// correctAnswer: ''
}
]);
```
- enum 값 찍어보면 0, 1 이런 식으로 나와서 알아보기 쉽게 값 넣었습니다.
quizzes.ts
```ts
export enum QuestionType {
objective = 'objective',
subjective = 'subjective'
}
```
- enum 타입은 impot 시에 type 을 붙이니 에러가 떠서 우선 따로 써놨습니다..
QuizForm.tsx
```tsx
import type { Question } from '@/types/quizzes';
import { QuestionType } from '@/types/quizzes';
```
- 우선 문항별로 타입 잘 바뀌지만.. 라디오 표시가 한 문제에만 뜨는게 문제입니다..
=> [feat] QuizForm 에서 가져온 questions useState로 QuestionForm 구성

next.config.mjs, src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-117
- 해당 question의 option을 찾아서 content를 변경합니다.
```tsx
const handleChangeOption = (id: string, content: string, options: Option[], optionId: string) => {
setQuestions((prev) =>
prev.map((question) => {
return question.id === id
? {
...question,
options: options.map((option) => {
return option.id === optionId ? { ...option, content } : option;
})
}
: question;
})
);
};
```
- StrictMode 태그 찾아서 지우려했는데 추가해야하는 것이었습니다..
next.config.mjs
```mjs
const nextConfig = {
reactStrictMode: false,
images: {
remotePatterns: [
{
protocol: 'https',
hostname: 'via.placeholder.com'
}
]
}
};
```
```
```
=> [feat] 선택지 입력값 quiz 의 useState 에 반영되게

src/api/quizzes.ts, src/app/(quiz)/(components)/QuizForm.tsx, src/components/common/BlueInput.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-119
대략적인 레이아웃을 보기 위한 임시 스타일링입니다.
테일윈드를 통한 컴포넌트 테두리 스타일링 
```
border-solid border-b border-blue-500
```
=> [style] Header & Footer 임시 스타일링

src/app/(community)/(components)/CommunityForm.tsx, src/app/(community)/(components)/CommunityMenu.tsx, src/types/posts.ts
🔗 
type/posts.ts export 설정이 누락돼있어서 추가로 머지 올립니다
```
```
=> [fix] type/posts.ts export 설정

tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-142
```
colors: {
bgColor1: '#FDF8F1',
bgColor2: '#F0F7FF',
pointColor1: '#2B84ED',
pointColor2: '#FF8878'
},
```
=> [style] tailwind Config 색상 정보 추가

src/app/(quiz)/(components)/QuizForm.tsx, src/app/(quiz)/(components)/QuizList.tsx, src/app/(quiz)/(components)/SelectQuizLevel.tsx, src/app/(quiz)/quiz-list/page.tsx, src/components/common/SubHeader.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-121
=> [style] Header & Footer 위치 fixed 및 스타일 조정

src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-136
- 퀴즈쪽이랑 가져오는게 약간 달라서 공통 함수 정리하면서 맞추면 될거 같습니다!
- url 로 변경해서 미리보기까지는 됐는데 파일 형태는 어디에 저장해둬야 할지 고민입니다..
QuizForm.tsx
```tsx
const handleChangeImg = (e: React.ChangeEvent<HTMLInputElement>) => {
const file = e.target.files?.[0];
if (file) {
setFile(file);
const reader = new FileReader();
reader.onloadend = () => {
setSelectedImg(reader.result as string);
};
reader.readAsDataURL(file);
}
};
<input
onChange={handleChangeImg}
/>
```
```tsx
const handleChangeImg = (id: string, files: FileList | null) => {
const file = files?.[0];
if (file) {
const reader = new FileReader();
reader.onloadend = () => {
setQuestions((prev) =>
prev.map((question) => {
return question.id === id ? { ...question, imgUrl: reader.result as string } : …
```
=> [feat] 이미지 미리보기, url setState

src/app/(quiz)/(components)/QuestionForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-160
- 저희 태그 속성 순서도 정하면 좋을 듯 합니다.. (className 을 가장 마지막에 두거나..?!)
```tsx
<input
type="checkbox"
className="w-[42px] h-[42px]"
checked={option.isAnswer}
onChange={() => {
handleCheckObjectAnswer(id, options, option.id);
}}
/>
```
=> [style] title, options CSS 작업

src/app/(quiz)/(components)/QuestionForm.tsx, src/app/(quiz)/(components)/QuizForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-154
- 이미지 input 을 getElementById 로 접근하던 방식 말고,
label for & input id 를 연결해서 클릭되도록 했습니다.
- 그래서 원래 div 에 있던 이 클릭만 넘겨주는 함수를 없앴습니다!
- SSR, CSR 문제인거 같은데 지영님이랑 같이 해결해보겠습니다..
- 리액트에서 getElement 로 DOM 요소 접근은 하면 안되고, 꼭 필요하면 useRef 를 써야한다고 합니다!
- getElement 때문에 id 인식이 잘못돼서 첨부가 됐다가 안됐다가 하는거 같다고 피드백 받았습니다.
=> [fix] 이미지 input DOM id 인식 오류 해결 - DOM 직접 접근 말고 label 로 연결

src/app/menu/page.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-152
jotai로 메뉴 모달의 열림/닫힘 상태를 관리를 통해 onClick으로 페이지 이동시 메뉴 모달창 자동으로 닫히게 구현
=> [feat] 메뉴 모달창 페이지 이동시 자동 닫힘 구현

src/app/(quiz)/(components)/QuestionForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-169
- 렌더 타이밍 때문에 생긴 문제라 로드가 된 뒤에 이미지가 렌더링 되도록 수정했습니다!
```tsx
const [loaded, setLoaded] = useState(false);
setLoaded(true);
}, [setLoaded]);
```
```tsx
{loaded && <InputQuestionImg id={id} img_url={img_url} onChange={handleChangeImg} />}
```
=> [fix] Worning: prop 'id' did not match. useEffect 로 해결

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/app/(non-auth)/terms/page.tsx, src/app/globals.css, src/app/page.tsx, src/components/layout/Header.tsx, src/hooks/useAuth.ts, yarn.lock
🔗 https://coding-legend.atlassian.net/browse/MMEASY-134
🔗 https://coding-legend.atlassian.net/browse/MMEASY-168
소셜 로그인시 일반적인 로그인과는 다르게 supabase profiles 테이블에 정보가 insert가 되지않는 문제가 있었는데,
외부 페이지에서 로그인하면서 자동으로 홈으로 라우팅 되기때문에 로그인 페이지에 작성한 정보를 전달해주는 로직이 실행 되지도 못하고 
넘어감으로써 문제가 발생한것으로 추정됌. 따라서 로그인 페이지가 아닌 홈 페이지에서 useEffect를 사용해 정보를 추가 해주는 로직을 작성해줌으로써 문제 해결
소셜 로그인 같은 외부 페이지에서 로그인을 하는경우에는 정보 추가 같은 로직을 로그인 페이지에 작성해주면 작동이 안된다는것을 알게 됨.
=> [feat] 회원가입 페이지 css 변경 소셜 로그인 정보 추가 구현

src/app/(quiz)/(components)/QuizForm.tsx, src/components/common/BlueInput.tsx, src/hooks/useConfirmPageLeave.tsx, src/utils/supabase/storage.ts
supabase storage에 올린 이미지 주소가 길어져서 반복되는 부분을 변수화했습니다.
* `utils/supabase/storage.ts`
```
export const storageUrl = 'https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public';
```
* 이렇게 넣어주세효
```
img_url: `${storageUrl}/quiz-thumbnails/tempThumbnail.png`
```
=> [chore] supabase storage 주소 변수화

src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-223
- 메뉴 페이지 관련 코드들은 우선 주석처리 해놨습니다.
- 클릭한 메뉴 아래에 생기는 바 나중에 해보겠읍니다..
=> [fix] 메인 헤더에 메뉴 표시 및 링크 연결

src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-223
=> [fix] 헤더 메뉴 다시 추가

src/app/(quiz)/(components)/QuizForm.tsx, src/app/profile/MyLevelAndScore.tsx, src/app/profile/MyProfile.tsx, src/app/profile/VerticalBlueLine.tsx, src/app/profile/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-234
=> [style] profile 페이지 UI 완성

src/api/game_scrore.ts, src/api/questions.ts, src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/QuestionEx.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/typing-game/page.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-253
=> [feat] 메인 페이지 퀴즈 수정, 타자 연습 랭킹 구현

src/app/(main)/(components)/CommunitySection.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-257
커뮤니티 부분 2개의 section이 세로로 정렬되는 문제 수정했습니다!
=> [fix] 메인페이지 css수정

src/app/(main)/(components)/Footer.tsx, src/app/(quiz)/(components)/QuizList.tsx, src/app/page.tsx
🔗https://coding-legend.atlassian.net/browse/MMEASY-261
=> [feat] 메인 페이지 Footer 

src/api/quizzes.ts, src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/typing-game/page.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-254
랭킹을 불러올때 이미지가 없으면 에러가 발생해 
```
{quizRank.avatar_img_url && (
<div className="mr-4 rounded-full overflow-hidden border-2 border-solid border-pointColor1 flex-shrink-0">
<Image
src={quizRank.avatar_img_url}
alt="프로필 이미지"
width={60}
height={60}
className="object-cover"
/>
</div>
)}
```
이런식으로 이미지를 불러올때만 avatar를 렌더링 하도록 변경했습니다.
=> [feat] 퀴즈 만든 수 랭킹 구현 , 버그수정

src/app/page.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-265
소셜 로그인으로 회원가입 할 시 로컬 스토리지 사용하던 부분 쿠키로 수정했습니다.
```
const saveUserProfile = async () => {
const { data: session } = await supabase.auth.getSession();
if (session) {
const user = session.session?.user;
if (user) { 
const id = user.id
const email = user.email ?? '';
const nickname = email.split('@')[0];
```
=> [fix] 소셜 로그인 회원가입 로직 수정

src/app/profile/MyProfile.tsx, src/app/profile/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-266
=> [feat] profile 페이지에서 로그인 유저의 정보 불러오기

src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-272
=> [feat] 타자연습 로그인 확인 모달

src/app/(quiz)/(components)/QuizList.tsx, src/app/(quiz)/(components)/SelectQuizLevel.tsx, src/components/common/RecommendLoginModal.tsx, src/store/store.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-274
🔗 https://coding-legend.atlassian.net/browse/MMEASY-260
- common 폴더에 RecommendLoginModar.tsx 만들어서 사용했는데 아마 타자 쪽이랑 넘겨주는 값이 달라서.. 나중에 같이 활용할 수 있게 수정하겠습니다..
=> [feat] 퀴즈 리스트에서 로그인 여부 확인 & 만들기 클릭 시 로그인 필요 알림 toast & 퀴즈 풀기 Link =>

src/api/users.ts, src/app/profile/MyLevelAndScore.tsx, src/app/profile/MyProfile.tsx, src/app/profile/mutations.tsx, src/app/profile/page.tsx, src/types/users.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-276
* useEffect로 데이터를 불러올 때 뭔가 이상하다고 느꼈어야 했는데 .. useQuery로 서버데이터상태 관리합시다...
* 기존 코드: 로그인 상태 체크 뿐만 아니라 데이터 가져오는 것까지 useEffect에서 이루어지고있음
```
/** 현재 로그인되어 있는지 확인 */
const fetchData = async () => {
try {
const getSession = await supabase.auth.getSession();
if (!getSession.data.session) {
alert('로그인이 필요한 페이지입니다.');
router.replace('/login');
} else {
const userProfile = await getCurrentUserProfile();
setCurrentUser((prev) => userProfile);
console.log('끼이잉', currentUser);
}
console.error('프로필 정보를 가져오는 데 실패했습니다:', error);
}
};
fetchData();
}, [isLoggedIn]);
```
* 변경된 코드: useEffect로는 로그인 여부만 확인하고, 데이터 가져오는 건 useQuery로 변경
```
/** 현재 로그인되어 있는지 확인 */
const fetchData = async () => {
try {
const …
```
=> [feat] 프로필 수정하기 구현 완료

src/app/(non-auth)/signup/page.tsx, src/app/admin/page.tsx, src/app/typing-game/page.tsx, src/hooks/useAuth.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-103
=> [feat] 중복 이메일 가입 방지 , 타자 연습 모달 버튼 위치 수정

src/app/page.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-280
=> [fix] 로그인시 사용자 정보 없을때만 정보 저장 로직 실행

src/api/tries.ts, src/app/(quiz)/quiz/[id]/Creator.tsx, src/app/(quiz)/quiz/[id]/mutation.ts, src/app/(quiz)/quiz/[id]/page.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-259
```tsx
const quizTry = {
user_id: currentUser,
quiz_id: id,
score: level * countCorrect * 100
};
const { data: quizTryData } = await supabase
.from('quiz_tries')
.select('*')
.eq('user_id', currentUser)
.eq('quiz_id', id);
if (quizTryData?.length !== 0) { // 데이터가 있다면 update
updateQuizMutation.mutate(quizTry);
return;
}
if (currentUser) { // 처음 풀고 로그인 상태면 insert, 비로그인 시엔 결과 페이지만 보여줌
insertQuizMutation.mutate(quizTry);
}
```
=> [feat] 퀴즈 점수 DB 에 insert, 풀었던 문제라면 update

src/app/(main)/(components)/RankingSection.tsx, src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/app/(non-auth)/terms/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-283
=> [style] 로그인/회원가입 페이지 메인 영역 높 84vh 조정

src/api/game_scrore.ts, src/api/tries.ts, src/app/(main)/(components)/RankingSection.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-300
=> [feat] 랭킹 로직 수정 

src/api/game_scrore.ts, src/api/tries.ts, src/app/(main)/(components)/RankingSection.tsx, src/app/typing-game/page.tsx, src/types/game.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-300
=> [feat] 랭킹 로직 수정 진짜 최종

src/api/comments.ts, src/api/posts.ts, src/app/(community)/(components)/Comment.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/my-activity/MyActivity.tsx, src/components/common/DeleteButton.tsx, src/components/common/EditButton.tsx, src/components/common/PostDeleteButton.tsx, src/components/common/PostEditButton.tsx, src/types/posts.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-292
각 카테고리별로 해당된 버튼들 추가하고 기능 구현했습니다.
- 내가 만든 퀴즈 -> 다시 풀러가기
- 내가 작성한 게시글 -> 삭제기능
- 내가 작성한 댓글 -> 삭제기능
```
```
```
```
=> [feat] my-activity 페이지 카테고리별 해당된 버튼 기능 추가

src/app/my-activity/MyActivity.tsx, src/components/common/DeleteButton.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-290
- 현재 내가 푼 문제는 데이터가 없어서 비어있습니다.
- 피그마에서는 게시글 이동만 있고 삭제가 없는데 댓글도 삭제 있으면 게시글도 있는게 좋지않을까..? 싶습니다
상세 정보로 가는건 제목 클릭만 해서 가도 상관 없을 것 같구요..
- 내가 만든 문제도 원래 삭제버튼이지만 일단은 다시풀기 버튼 구현 상태 확인때문에 대신 넣어뒀습니다
```
```
```
```
=> [feat] my-activity CSS

src/app/(community)/(components)/Comment.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/(main)/(components)/RankingSection.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-307
사용자가 첨부한 이미지에 따라서 동그라미 모양이 납작해보이던 부분을 수정했습니다
이미지를 감싼 div의 높낮이를 설정해주시고, 이미지 클래스에는 w-full h-full object-cover 주시면 됩니당
```
<div className="w-[50px] h-[50px] m-5 ml-0 flex justify-center rounded-full overflow-hidden">
<Image
src={`${profileStorageUrl}/${prev.profiles?.avatar_img_url || '프로필이미지'}`}
alt="프로필이미지"
width={50}
height={50}
className="w-full h-full object-cover"
/>
</div>
```
=> [style] 프로필 이미지 동그라미로 수정

src/api/quizzes.ts, src/app/(main)/(components)/Footer.tsx, src/app/layout.tsx, src/app/styles/font.ts, src/app/typing-game/page.tsx, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-308
- 가능한 wetigh 전부 넣어놨는데 font-extrabold 랑 font-black 이 굵기가 같더라구요. 가장 굵은거 쓰고 싶으시면 font-black 쓰시면 될 거 같습니다!
- 기본 굵기 = font-normal = 400
app/styles/font.ts
```ts
import { Gothic_A1 } from 'next/font/google';
export const gothic_a1 = Gothic_A1({
subsets: ['latin'],
weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
display: 'swap'
});
```
app/layout.tsx
```tsx
import { gothic_a1 } from './styles/font';
return (
<html lang="en">
<body className={gothic_a1.className}>
```
=> [style] 폰트 Gothic A1 으로 변경

src/app/(quiz)/(components)/SelectQuizLevel.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-311
- 나중에 순한 맛이 맨 앞에 오도록 수정해야 할 거 같습니다..
=> [style] 퀴즈 레벨 이미지 기울임, 겹치기, 보더 스타일 조정

src/api/tries.ts, src/app/profile/MyLevelAndScore.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-278
=> [feat] 프로필 퀴즈점수 불러오기, 합한 점수 표시

src/app/(non-auth)/signup/page.tsx, src/app/admin/page.tsx, src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-366
```
const newTotalScore = finalScore;
const { error: updateError } = await supabase
.from('game_tries')
.update({ score: newTotalScore })
.eq('user_id', user.id);
if (updateError) throw updateError;
```
const newTotalScore = existingScores.score + finalScore;에서 수정
=> [fix] 타자연습 점수 누적 삭제

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-317
=> [style] 로그인,회원가입 이미지 수정, 타자연습 점수저장 로직 수정

src/api/quizzes.ts, src/app/my-activity/MyActivity.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-295
- my-activity 에서 사용자가 푼 퀴즈 리스트를 불러왔습니다.
- 화면 비율을 추가적으로 작업하겠습니다.
```tsx
export const userSolvedQuizzes = async (email: string) => {
try {
const { data, error } = await supabase
.from('quiz_tries')
.select(`*,quizzes:quiz_id (id, title)`)
.eq('user_id', email);
if (error) throw error;
return data;
console.error('사용자 퀴즈 불러오기 실패', error);
}
};
```
```tsx
// 사용자가 푼 quiz 불러오기
const {
data: userSolvedQuiz,
isLoading: isSolvedQuizLoading,
isError: isSolvedQuizError
} = useQuery({
queryFn: async () => {
try {
const userProfile = await getCurrentUserProfile();
if (userProfile && userProfile.email) {
return await userSolvedQuizzes(userProfile.email);
}
return [];
console.error('퀴즈 불러오기 실패:', error);
throw …
```
=> [feat] my-activtiy 내가 푼 퀴즈 불러오기

src/app/(community)/community-list/page.tsx, src/app/my-activity/MyActivity.tsx, src/app/my-activity/Pagination.tsx
=> [style] my-activity css 비율 수정

src/app/(community)/(components)/DetailPost.tsx, src/app/(quiz)/quiz/[id]/page.tsx, src/components/common/ReportButton.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-376
🔗 https://coding-legend.atlassian.net/browse/MMEASY-377
🔗 https://coding-legend.atlassian.net/browse/MMEASY-378
🔗 https://coding-legend.atlassian.net/browse/MMEASY-379
ReportButton.tsx
```tsx
/** 이 퀴즈/포스트의 신고 이력을 가져옴 */
const { data: adminData } = await supabase.from('admin').select('*').eq('target_id', targetId);
const adminId = adminData && adminData.length > 0 ? adminData?.[0].id : null;
/** 신고 이력이 없다면 admin에 최초 신고 등록 */
if (adminData?.length === 0) {
const insertedAdminId = await insertAdminMutation.mutateAsync(admin);
const report = {
user_id: currentUserEmail,
admin_id: insertedAdminId  // 방금 admin 에 등록된 id
};
insertReportMutation.mutate(report); // report 에 같이 등록
toast.success('신고가 등록되었습니다.');
return;
} else {
/** admin에 신고 …
```
=> [feat] 로그인 여부, 신고 등록 이력(admin) 여부, 현재 사용자의 신고(reports) 여부에 따른 신고 처리

src/api/posts.ts, src/app/(community)/(components)/DetailPost.tsx, src/app/(community)/community-list/page.tsx, src/app/profile/MyLevelAndScore.tsx, src/components/common/ReportButton.tsx, src/types/posts.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-385
=> [feat] 커뮤니티 신고 기능 추가

src/api/admin.ts, src/app/admin/page.tsx, src/types/admin.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-386
🔗 https://coding-legend.atlassian.net/browse/MMEASY-387
=> [feat] 어드민 페이지 신고글 불러오기 및 제목 클릭시 이동 구현

src/app/admin/page.tsx, src/components/layout/Header.tsx, src/types/users.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-388
```
const fetchData = async () => {
try {
const getSession = await supabase.auth.getSession();
if (!getSession.data.session) {
return;
} else {
setIsLoggedIn(true);
setCurrentUserEmail(getSession.data.session.user.email);
}
console.error('프로필 정보를 가져오는 데 실패했습니다:', error);
}
};
```
```
{currentUserEmail === 'daejang@mmeasy.com' && (
<Link href="/admin">Admin</Link>
)}
```
=> [feat] 어드민 조건부로 헤더에 표시

src/app/admin/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-391
🔗 https://coding-legend.atlassian.net/browse/MMEASY-392
신고, 복구 시 admin에 해당하는 게시글,퀴즈 stauts값 변경 되도록 했고, 해당하는 게시글,퀴즈에 deleted_at에 값을 넣어주거나 null값으로 변경되게 구현했습니다.
=> [feat] 신고 삭제 복구 구현

src/app/(community)/(components)/CommunityForm.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/(community)/(components)/EditForm.tsx, src/app/(community)/(components)/NoticeEditor.tsx, src/app/(community)/(components)/PostForm.tsx, src/app/my-activity/MyActivity.tsx, src/app/my-activity/Pagination.tsx, src/components/common/DeleteButton.tsx
커뮤니티 페이지 bgColor 없던거 추가하고 상세 페이지 내용 길이에 따라 카테고리 영역 늘어나도록 수정했습니다
=> [style] 커뮤니티, 나의 활동 페이지 css 수정

src/app/about/page.tsx, src/app/globals.css
🔗 https://coding-legend.atlassian.net/browse/MMEASY-394
- 소개페이지의 유저후기부분에 말풍선 css 추가 하였습니다. 
- globals.css에 있습니다. 
```
.about-userreviewright {
position: relative;
}
.about-userreviewright::after {
content: '';
display: block;
position: absolute;
bottom: -20px;
right: 60px;
border-color: #2b84ed transparent;
border-style: solid;
border-width: 0px 16px 20px 16px;
transform: rotate(180deg);
z-index: 0;
}
.about-userreviewright::before {
content: '';
display: block;
position: absolute;
border-color: white transparent;
border-style: solid;
border-width: 0px 16px 20px 16px;
transform: rotate(180deg);
bottom: -18.5px;
right: 60px;
z-index: 1;
}
```
=> [style] 소개페이지 유저후기 말풍선 css

src/app/(community)/(components)/CommunityMain.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/(community)/(components)/Like.tsx, src/app/(main)/(components)/Banner.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(quiz)/(components)/InputQuestionImg.tsx, src/app/(quiz)/(components)/QuestionForm.tsx, src/app/page.tsx, src/components/common/ReportButton.tsx, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-396
- 처음 로드 시에 랜덤 index 를 받도록 했습니다.
Banner.tsx
```tsx
const banners = ['banner_v2_b.png', 'banner_v2_lb.png'];
const [randomIdx] = useState(Math.floor(Math.random() * banners.length));
```
- 시연 영상 촬영때문에 커뮤니티 mt 조금 넓혀놨습니다! 나중에 다시 조정하겠습니다!
=> [style] 배너 랜덤 설정 및 커뮤니티 좋아요/신고 CSS 수정

src/app/(community)/(components)/CategorySelector.tsx, src/app/(community)/(components)/CommunityForm.tsx, src/app/(community)/(components)/CommunityMain.tsx
=> [style] 커뮤니티 css 수정

src/api/game_scrore.ts, src/api/quizzes.ts, src/api/tries.ts, src/app/typing-game/page.tsx, src/utils/date.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-417
sql 을 사용해 일주일 단위로 필터링 되게 수정
=> [feat] 랭킹 일주일 단위로 수정

src/api/quizzes.ts, src/app/(quiz)/quiz/[id]/mutations.ts, src/app/(quiz)/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-364
=> [feat] 퀴즈 풀기 페이지에서 내가만든 퀴즈인경우 삭제 구현 

src/api/tries.ts, src/app/profile/MyLevelAndScore.tsx, src/types/quizzes.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-418
- 같은 테이블을 두 번 불러오고 있어서 생긴 오류였습니다! 하나만 남겨두고 정리했습니다.
MyLevelAndScore.tsx
```tsx
/** 내가 푼 퀴즈 가져오기 */
export const getQuizzesISolved = async (id: string): Promise<QuizTry[]> => {
try {
const { data, error } = await supabase.from('quiz_tries').select('*').eq('user_id', id);
if (error) throw error;
return data;
console.error('내가 푼 퀴즈 데이터 받아오기 실패', error);
alert('일시적으로 내가 푼 퀴즈 데이터를 받아오지 못했습니다. 다시 시도하세요.');
throw error;
}
};
/** quiz_tries 테이블에서 나의 점수만(score컬럼) 가져오기 */
// export const getMyQuizScore = async (user_id: string): Promise<number> => {
//   try {
//     let { data: myQuizScores, error } = await supabase.from('quiz_tries').select('score').eq('user_id', user_id);
//     if (error) throw error;
//     const …
```
=> [fix] 나의 프로필 페이지 퀴즈 점수 불러오기 에러 해결

src/app/profile/MyLevelAndScore.tsx
=> [fix] 로딩 메세지 수정

src/app/(quiz)/(components)/QuizList.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-420
=> [style] 퀴즈리스트 보더 색상

src/app/about/page.tsx, src/app/globals.css
🔗 https://coding-legend.atlassian.net/browse/MMEASY-419
- 소개페이지 변경사항에 최대한 맞췄습니다.. 말풍선 뾰족한부분 위치도 바꿨습니다.
=> [style] 소개페이지 css 변경사항 수정

src/app/(community)/(components)/CommunityForm.tsx, src/app/(community)/(components)/CommunityMain.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/(community)/(components)/PostForm.tsx, src/app/(quiz)/quiz/[id]/mutations.ts, src/app/my-activity/MyActivity.tsx, src/components/common/ReportButton.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-423
🔗https://coding-legend.atlassian.net/browse/MMEASY-424
- 공지 색 , 닉네임 비율 수정
- 신고 위치 조정
현재 공지글이 최상단에 위치하긴 하는데 게시글이 추가되면 다음 페이지로 넘어가져서... 이후에 형민님이랑 수정해보겠습니다
=> [feat] 신고버튼 위치 조정 / 공지글 색 변경

src/app/profile/MyLevelAndScore.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-279
MyLevelAndScore.tsx
```tsx
const myLevel =
myTotalScore < 5000 ? 1 : myTotalScore < 15000 ? 2 : myTotalScore < 35000 ? 3 : myTotalScore < 70000 ? 4 : 5;
```
=> [feat] 나의 프로필에 총 점수에 따라 level 표시

src/app/about/page.tsx
- 기존에는 페이지 이동을 하였는데 새창으로 열리게 바꾸었습니다.
=> [fix]소개페이지 팀 정보 버튼 수정

src/api/posts.ts, src/api/quizzes.ts, src/app/(community)/(components)/CommunityForm.tsx, src/app/(community)/(components)/DetailPost.tsx, src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-426
🔗 https://coding-legend.atlassian.net/browse/MMEASY-427
=> [feat] 메인페이지 퀴즈 최신순 수정, 커뮤니티 관리자 삭제버튼 추가

src/app/quiz/list/SelectQuizLevel.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-434
=> [fix] 헤더 퀴즈 페이지 링크 수정

src/api/game_scrore.ts, src/api/quizzes.ts, src/api/tries.ts, src/types/game.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-444
=> [feat] 랭킹 날짜 수정

src/app/community/list/[category]/[id]/DetailPost.tsx, src/app/community/list/[category]/[id]/edit/page.tsx, src/app/community/list/[category]/[id]/page.tsx, src/app/community/list/[category]/layout.tsx, src/app/community/list/[category]/page.tsx, src/app/community/write/PostEditor.tsx, src/app/community/write/TextEditor.tsx, src/app/community/write/layout.tsx, src/app/community/write/page.tsx
- 커뮤니티 전반적으로 CSS 화면에 맞게 수정했습니다
=> [feat] 커뮤니티 css 수정

src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/page.tsx, src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-446
🔗 https://coding-legend.atlassian.net/browse/MMEASY-445
- 화면 가로길이가 1440보다 크다면 게임 넓이를 1440 으로 설정하고, 작다면 full 로 설정합니다.
typing-game.tsx
```tsx
// window 객체가 있는지 확인하여 서버 사이드에서 실행될 때 오류 방지
if (typeof window !== 'undefined') {
if (window.innerWidth > 1440) {
setGameAreaWidth(1440);
} else {
setGameAreaWidth(window.innerWidth);
}
}
}, []);
```
- 타자연습 배경화면 이미지가 크기가 커서 페이지가 전체적으로 느리더라구요. 🥲
우선 이미지는 빼놨고, 내일 디자이너님한테 작은 파일로 부탁드려야 할 거 같습니다!
=> [style/fix] 

src/app/community/list/[category]/[id]/edit/page.tsx, src/app/community/write/layout.tsx, src/app/community/write/page.tsx, src/app/typing-game/page.tsx, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-447
tailwind.config.ts 에 애니메이션 추가했습니다
```
keyframes: {
'wave-opacity': {
'0%, 100%': { opacity: 1 as any },
'50%': { opacity: 0.4 as any }
},
'hover-opacity': {
'from, to': { opacity: 1 as any }
},
slash: {
'from': {
transform: 'rotate(-45deg) translateX(-100%)', 
opacity: 0 as any
},
'to': {
transform: 'rotate(-45deg) translateX(100%)',
opacity: 1 as any
}
}
},
animation: {
'wave-opacity': 'wave-opacity 3s ease-in-out infinite',
'hover-opacity': 'hover-opacity 0.3s ease-out',
slash: 'slash 0.75s ease-out forwards'
}
```
=> [style] 타자연습 버튼 애니메이션 추가

src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-449
=> [fix] 타자연습 난이도 조정

.gitignore, src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/app/typing-game/page.tsx, src/components/layout/ProfileDropdown.tsx, src/utils/supabase/storage.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-452
🔗 https://coding-legend.atlassian.net/browse/MMEASY-453
- 로그인 이미지 url 을 없애고 assetsStorageUrl 를 추가해놨습니다! 현재 storage 파일에서 공유하고 있는 url 들입니다.
storage.ts
```ts
export const storageUrl = 'https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public';
export const assetsStorageUrl = 'https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public/assets';
export const profileStorageUrl = 'https://icnlbuaakhminucvvzcj.supabase.co/storage/v1/object/public/profile_imgs';
```
=> [fix] 스토리지 url assets 로 수정 & 로그아웃하면 메인페이지로 이동

src/api/comment.ts, src/app/community/list/[category]/CommunityForm.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-456
=> [style] 커뮤니티 각 게시글 댓글수 0일때 표시 하지 않기

src/app/admin/page.tsx, src/app/my-activity/MyActivity.tsx, src/app/quiz/list/SelectQuizLevel.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-457
=> [style] 관리자 페이지 버튼 css 변경

src/app/my-activity/MyActivity.tsx, src/app/my-activity/page.tsx
=> [style] 나의 활동 페이지 css

src/app/community/list/[category]/[id]/DetailPost.tsx, src/app/quiz/form/page.tsx, src/app/quiz/mutations.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-458
🔗 https://coding-legend.atlassian.net/browse/MMEASY-459
=> [fix] 퀴즈 등록시 토스트 여러번 뜨는거 수정

src/app/about/page.tsx, src/app/globals.css, src/app/my-activity/MyActivity.tsx, src/app/quiz/[id]/page.tsx, src/utils/managerData.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-460
managerData => utils 폴더로 이동했습니다.
=> [style] 소개 페이지 CSS 수정 중 & 퀴즈 삭제 버튼 위치 수정 & 나의 활동 중앙 표 수정

src/app/about/page.tsx, src/app/my-activity/MyActivity.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-460
🔗 https://coding-legend.atlassian.net/browse/MMEASY-461
=> [style] 소개 페이지 말풍선 width, 멤버 사이 gap 넓힘 & 나의 활동 테이블 heigth 고정

src/app/quiz/list/QuizList.tsx, src/app/quiz/list/SelectQuizLevel.tsx, src/components/layout/Header.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-464
🔗 https://coding-legend.atlassian.net/browse/MMEASY-462
🔗 https://coding-legend.atlassian.net/browse/MMEASY-463
- 화면이 줄어들면 오른쪽 애들처럼 이미지가 짤리고 있어서 순한맛처럼 수정했습니다!
- 리스트 비율 꽉차게 수정했습니다!
=> [style] 헤더 반응형으로 수정 & 레벨 이미지 화면 줄어도 잘리지 않게 & 퀴즈 리스트 너비 꽉차게

src/app/quiz/list/SelectQuizLevel.tsx, src/components/common/PageUpBtn.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-471
=> [fix] quiz list 무한데이터로딩 수정..

src/app/(non-auth)/signup/page.tsx, src/hooks/useAuth.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-473
=> [fix] 이메일 유효성 검사 추가

src/app/layout.tsx, src/app/my-activity/MyActivity.tsx
- 기존 퀴즈 삭제에서 queryKey 수정하여 적용했습니다
```
const handleDeleteQuiz = (id: string) => {
if (!window.confirm('해당 퀴즈를 삭제하시겠습니까?')) return;
deleteQuizMutation.mutateAsync(id).then(() => {
queryClient.invalidateQueries({
queryKey: ['userQuizzes']
});
});
};
```
=> [feat] 나의 활동에서 내가만든 퀴즈 삭제 시 바로 반영

src/app/(non-auth)/signup/page.tsx
=> [fix] 회원가입 라우터 주석 품

src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/(non-auth)/signup/page.tsx, src/constant/locales/home/community-section.ts, src/constant/locales/home/quiz-section.ts, src/constant/locales/home/ranking-section.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-495
=> [feat] 메인 페이지 UI 번역

src/app/(main)/(components)/RankingSection.tsx, src/app/(non-auth)/signup/page.tsx, src/components/layout/Header.tsx, src/constant/locales/components/header.ts, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-496
🔗 https://coding-legend.atlassian.net/browse/MMEASY-497
회원가입시 비밀번호 조건을 영문,숫자,특수문자 조합 8자 이상으로 설정했고,
메인 페이지에서 랭킹을 새로 받아올수있는 새로고침 버튼을 추가하였습니다.
=> [feat] 메인 페이지 랭킹 새로고침 버튼, 회원가입 비밀번호 조건 수정

src/app/my-activity/MyActivity.tsx, src/app/profile/MyLevelAndScore.tsx, src/app/profile/MyProfile.tsx, src/constant/locales/my-page/my-activity.ts, src/constant/locales/my-page/my-profile.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-498
=> [feat] 나의 프로필 & 나의 활동 UI 번역

src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/about/page.tsx, src/app/my-activity/MyActivity.tsx, src/app/profile/MyLevelAndScore.tsx, src/app/profile/MyProfile.tsx, src/app/quiz/[id]/Creator.tsx, src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/page.tsx, src/app/quiz/form/InputQuestionTitle.tsx, src/app/quiz/form/PlusQuestionBtn.tsx, src/app/quiz/form/QuestionForm.tsx, src/app/quiz/form/QuizForm.tsx, src/app/quiz/form/page.tsx, src/app/quiz/list/SelectQuizLevel.tsx, src/app/typing-game/page.tsx, src/components/common/BlueInput.tsx, src/components/layout/Header.tsx, src/components/layout/ProfileDropdown.tsx, src/constant/locales/my-page/my-profile.ts, src/constant/locales/quiz/quiz-try.ts, src/constant/locales/typing-game/typing-game.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-502
=> [feat] 타자연습, 퀴즈 풀기 UI 번역 & 안쓰이는 setLang 제거 & about 멤버 lg:grid 수정

src/app/quiz/[id]/Options.tsx, src/app/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-514
- input 을 div 로 감싸고 있었는데, label 로 감싸게 수정했습니다!
Options.tsx
```tsx
<div>
<input type="radio"
onChange={() => onChange(questionId, is_answer, id)}
checked={usersAnswer?.option_id === id}
/>
<p>{content}</p>
</div>
```
```tsx
<label>
<input type="radio"
onChange={() => onChange(questionId, is_answer, id)}
checked={usersAnswer?.option_id === id}
/>
{content}
</label>
```
=> [fix] 객관식 옵션 radio 뿐 아니라 옵션 전체 선택 가능하도록

src/app/(non-auth)/login/page.tsx, src/app/(non-auth)/signup/page.tsx, src/constant/PrivacyPolicy.tsx, src/constant/Terms.tsx, src/constant/locales/components/header.ts, src/constant/locales/login/login.ts, src/constant/locales/login/privacypolicy.ts, src/constant/locales/login/signup.ts, src/constant/locales/login/terms.ts, src/constant/locales/typing-game/typing-game.ts, src/utils/useMultilingual.ts, tailwind.config.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-515
🔗 https://coding-legend.atlassian.net/browse/MMEASY-516
🔗 https://coding-legend.atlassian.net/browse/MMEASY-517
=> [feat] 로그인, 회원가입 UI 번역, 회원가입 비밀번호 확인 일치 불일치 표시 추가

src/app/quiz/[id]/CorrectAnswerBtn.tsx, src/app/quiz/[id]/Options.tsx, src/app/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-518
- 문제마다 showCorrectAnswer state 를 만들고 버튼 클릭 시 상태 바뀌도록 했습니다.
CorrectAnswerBtn.tsx
```tsx
const CorrectAnswerBtn = ({ answer }: { answer: string | undefined }) => {
const [showCorrectAnswer, setShowCorrectAnswer] = useState(false);
const handleShowCorrectAnswer = () => {
setShowCorrectAnswer(!showCorrectAnswer);
};
return (
<section className="h-5 flex justify-end gap-2 leading-5 text-pointColor1">
{showCorrectAnswer && <p>{answer}</p>} // 표시할 정답
<button onClick={handleShowCorrectAnswer}> // 펜 아이콘
<FaHighlighter className="text-pointColor1 text-lg" />
</button>
</section>
);
};
```
=> [feat] 각 문제마다 정답 보기 버튼 추가

src/app/quiz/[id]/Creator.tsx, src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/page.tsx, src/components/common/ReportButton.tsx, src/types/reports.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-519
🔗 https://coding-legend.atlassian.net/browse/MMEASY-521
ReportButton.tsx
```tsx
const reasonForReport = window.prompt('신고 사유를 입력해 주세요.'); // 신고 이력이 없다면 사유를 받음
if (reasonForReport) {
const report = {
title,
target_id: targetId,
type,
reason: reasonForReport, // 사유 추가
reported_user_id: creatorId,
user_id: currentUserEmail
};
```
=> [style/feat] 퀴즈 풀기 X 버튼 크게 & 신고 사유 받기

src/app/quiz/list/SelectQuizLevel.tsx, src/app/typing-game/page.tsx, src/constant/locales/typing-game/typing-game.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-525
=> [fix] typing-game 페이지 언마운트 시 재생 오디오 정지

src/app/typing-game/page.tsx
=> [style] 게임 시작시 세로 높이 깨지지 않도록 수정

src/app/quiz/[id]/page.tsx, src/app/quiz/list/SelectQuizLevel.tsx, src/app/quiz/list/page.tsx, src/components/common/ReportButton.tsx, src/constant/locales/admin/reports.ts, src/constant/locales/quiz/quiz-try.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-522
🔗 https://coding-legend.atlassian.net/browse/MMEASY-523
SelectQuizLevel.tsx
```tsx
const handleScroll = () => {
const isAtBottom = Math.ceil(window.innerHeight + window.scrollY) >= document.body.offsetHeight;
```
=> [feat] 퀴즈 풀기, 신고 관련 toast 번역 & 무한스크롤 height ceil 적용

src/components/layout/Header.tsx, src/components/layout/ToggleLanguage.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-537
=> [style] Header 모바일 스타일

src/app/(non-auth)/login/page.tsx, src/app/typing-game/page.tsx, src/constant/locales/login/signup.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-539
🔗 https://coding-legend.atlassian.net/browse/MMEASY-540
=> [style] 로그인,회원가입 페이지 모바일 스타일

src/app/typing-game/page.tsx, src/constant/locales/typing-game/typing-game.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-541
=> [feat] 타자 연습 돌아가기 버튼 추가

src/app/(main)/(components)/CommunitySection.tsx, src/app/(main)/(components)/NewsSection.tsx, src/app/(main)/(components)/QuizSection.tsx, src/app/(main)/(components)/RankingSection.tsx, src/app/layout.tsx, src/app/quiz/[id]/CreateInfo.tsx, src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/page.tsx, src/constant/locales/quiz/quiz-try.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-542
=> [style] 퀴즈 풀기 페이지 모바일 CSS & 메인 섹션 헤더 w-full

src/app/typing-game/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-544
=> [fix] 타자 연습 나가기 버튼 엔터 비활성화

src/app/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-547
```tsx
const isAllAnswersSubmitted = questions.length === usersAnswers.length; // 문제 갯수와 답변 갯수 비교
<button // 길이가 같으면 파란색으로 표시
className={${isAllAnswersSubmitted ? 'bg-pointColor1' : 'bg-grayColor2 cursor-default'}`}>
```
=> [fix] 퀴즈 다 풀어야 제출 버튼 파란색으로 활성화

src/app/community/list/[category]/CategorySelector.tsx, src/app/community/list/[category]/layout.tsx
- params 를 받아서 params 가 있으면 hidden 을 적용하고 없으면 보여주도록 적용했습니다
```
const params2 = useParams<Params>();
console.log(params2.id);
<nav className={`${params2 && 'sm:hidden'}text-pointColor1 font-bold sm:font-normal sm:mx-4`}>
```
=> [fix] 상세페이지 카테고리 안나오는 현상 수정

src/app/community/list/[category]/[id]/Comment.tsx, src/app/community/list/[category]/layout.tsx, src/app/community/write/PostEditor.tsx, src/app/community/write/TextEditor.tsx, src/app/community/write/layout.tsx, src/app/community/write/page.tsx, src/app/globals.css, src/components/common/FormButtons.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-549
- React-quill 세부적인 수정이 조금 필요했어서 @media 사용해서 css 변경했습니다
```
@media (max-width: 480px) {
.ql-toolbar {
border-top: 1px solid #2B84ED !important;
border-bottom: 1px solid #2B84ED !important;
}
}
@media (max-width: 480px) {
.ql-container {
border-bottom: 1px solid #2B84ED !important;
height: 750px !important;
}
}
@media (max-width: 480px) {
.ql-formats {
margin-right: 10px !important;
}
}
```
=> [style] 커뮤니티 글쓰기 페이지 모바일 반응형

src/app/quiz/[id]/Header.tsx, src/app/typing-game/page.tsx, src/components/common/ExitButton.tsx, src/constant/locales/quiz/quiz-try.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-551
🔗 https://coding-legend.atlassian.net/browse/MMEASY-552
=> [fix] 그만 풀기 버튼 변경 & alert 번역

tailwind.config.ts
=> [style] bgColor4 블루 추가

src/app/typing-game/page.tsx
=> [fix] 타자 연습 게임 볼륨 슬라이더에 효과음 연결

src/api/game_scrore.ts, src/api/quizzes.ts, src/api/tries.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-579
랭킹 날짜를 24일로 수정 하였습니다.
=> [fix] 랭킹 날짜 수정

src/app/about/page.tsx, src/app/community/list/[category]/CategorySelector.tsx, src/app/community/list/[category]/CommunityForm.tsx, src/app/community/list/[category]/CommunityMain.tsx, src/app/my-activity/MyActivity.tsx, src/app/profile/MyLevelAndScore.tsx, src/app/profile/MyProfile.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-590
- pc
- 모바일
=> [style] My Activity 로딩 이미지, My Profile 프로필수정, 나의활동 버튼 bold 추가

src/app/phonics/PhonicsLayout.tsx, src/app/phonics/consonants/page.tsx, src/app/phonics/vowels/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-602
=> [feat] 파닉스 페이지 레이아웃 수정

src/app/phonics/consonants/page.tsx, src/app/phonics/vowels/page.tsx, src/constant/locales/hangul/consonants.ts, src/constant/locales/hangul/vowels.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-601
=> [feat] 파닉스 페이지 번역 완료

src/app/quiz/[id]/page.tsx, src/app/quiz/form/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-603
=> [feat] 퀴즈 관련 페이지에 모바일서브헤더 추가

src/app/phonics/PhonicsLayout.tsx, src/app/phonics/vowels/page.tsx
=> [style] 파닉스페이지 모바일 수정

next.config.mjs, src/components/common/CloudinaryImage.tsx, src/components/common/LoadingImg.tsx
=> [fix] 로딩 이미지 CDN 설정

src/app/phonics/PhonicsLayout.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-620
- 페이지 아래 약간 틈이 있어서 수정했습니다!
=> [style] 파닉스 카테고리 height 수정

src/app/phonics/PhonicsLayout.tsx, src/app/phonics/consonants/page.tsx, src/app/phonics/vowels/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-620
- 커뮤니티랑 카테고리 width 맞추려고 bg, border 수정했습니다!
=> [style] 파닉스 bg, border 수정

src/app/phonics/PhonicsLayout.tsx, src/app/quiz/form/QuestionForm.tsx, src/components/common/LoadingImg.tsx, src/constant/locales/components/loading.ts, src/constant/locales/hangul/phonics.ts, src/utils/useMultilingual.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-621
=> [fix] 로딩 페이지, 파닉스 카테고리 번역 & 퀴즈 옵션 추가 버튼 CSS 수정

src/app/(main)/QuestionEx.tsx, src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-622
currentUserEmail 이랑 creator 를 가져와서 Header.tsx 안에서 조건부 렌더링 했습니다.
```tsx
<Header
level={level}
title={title}
isAnswerWritten={usersAnswers.length}
resultMode={resultMode}
id={id}
currentUserEmail={currentUserEmail}
creator={creator_id}
/>
```
```tsx
{currentUserEmail === creator && (
<div className='pr-4 font-bold'>
<QuizDropdown
deleteBtn={
<CancelButton
text={m('DELETE_BTN')}
width="w-32"
height="h-12"
border="border-1"
onClick={() => handleDeleteQuiz(id as string)}
/>
}
/>
</div>
)}
```
=> [feat] 퀴즈 풀기페이지 퀴즈 삭제버튼 조건부 렌더링

src/app/layout.tsx
🔗https://coding-legend.atlassian.net/browse/MMEASY-528
=> [feat] 메타이미지 수정

src/app/community/list/[category]/page.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-633
- 로컬에서 한글로 해놓고 새로고침을 하면 에러가 뜨는 문제가 있었습니다. 배포에서는 에러는 화면에서 안 뜨지만 콘솔에서는 에러를 볼 수 있었습니다. 배포 콘솔 에러에서 Suspense 이야기가 있길래 한번 지워보았습니다.
-  Suspense는 데이터를 미리 로드하고 컴포넌트가 준비될 때까지 대기하는 데 사용되는 기능이며, 이를 잘못 구현하거나 사용할 때 발생할 수 있는 문제가 있습니다.
- 지우고 커뮤니티 각종 기능 테스트해봤는데 정상적으로 돌아가서 완전히 지웠습니다. 버셀에서 빌드도 확인했습니다.
=> [delete] Suspense 제거

src/api/quizzes.ts, src/app/quiz/[id]/SideHeader.tsx, src/app/quiz/[id]/mutations.ts, src/app/quiz/[id]/page.tsx, src/app/quiz/form/QuestionForm.tsx, src/app/quiz/form/QuizForm.tsx, src/app/quiz/form/edit/page.tsx, src/app/quiz/form/page.tsx, src/app/quiz/mutations.tsx, src/constant/locales/quiz/quiz-try.ts
🔗 https://coding-legend.atlassian.net/browse/MMEASY-365
퀴즈 수정하기 너무 어이없이 간단하게 해결됐습니다.
기존에 올라가 있는 내용을 일일이 수정하려고 생각해서 고생했었는데,
그냥 수정하기 버튼 클릭할 때마다 올라가 있는 내용을 다 지워버리고 새로 올리는 방식으로 해결했습니다.
=> [feat] 퀴즈 수정하기 기능 추가

src/app/quiz/[id]/Options.tsx
=> [feat] 퀴즈 옵션 기능 주석 추가

src/app/about/page.tsx
=> [fix] 소개페이지 띄어쓰기

src/components/main/QuizSection.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-641
=> [style] 메인 최근 퀴즈 이미지, 버튼 크기 padding 수정

src/components/main/NewsData.tsx, src/components/main/RankingSection.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-642
=> [feat] 메인 랭킹, 뉴스 더보기 버튼 aria label 추가

src/components/layout/Footer.tsx
🔗 https://coding-legend.atlassian.net/browse/MMEASY-642
=> [feat] footer 구글폼 아이콘 aria label 추가

src/app/profile/MyProfile.tsx
=> [style] 나의 프로필 페이지 기본 프로필 배경 흰색으로

src/app/quiz/[id]/Header.tsx, src/app/quiz/[id]/QuizDorpdown.tsx, src/components/layout/ProfileDropdown.tsx, src/constant/locales/components/header.ts
=> [feat] 로그아웃 toast 번역 & 퀴즈 풀기 레벨 웹, 모바일 수정
